.\" $Id$
.Dd May 22, 2005
.Dt NEWGRP 1
.Os
.Sh NAME
.Nm newgrp
.Nd change to new group
.Sh SYNOPSIS
.Nm newgrp
.Op Fl l
.Op Ar group
.Sh DESCRIPTION
The
.Nm
utility creates a new environment running with a 
.Pp
The following options are supported:
.Bl -tag -width Ds
.Op Fl l
.El
.Sh SEE ALSO
.Xr groups 1
